### ISSUE TITLE
RAM issue

### ISSUE THREAD

**Issue by TRvlvr** [tsurumeso/vocal-remover#16]
Current error:

_RuntimeError: CUDA out of memory. Tried to allocate 384.00 MiB (GPU 0; 6.00 GiB total capacity; 4.29 GiB already allocated; 299.14 MiB free; 52.89 MiB cached)_

I have the following PC specs -

**Operating System:** Windows 10
**Processor:** Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz 2.80 GHz
**Graphics card:** Geforce GTX 1060 with 6GB's of V-RAM
**System RAM:** 32GB

My issue is I can't even start training with my GPU due to always getting "out of RAM errors" even when I have enough allocated. I'm able to train just fine with my CPU, but I would really like to use my GPU.

**My questions:**

1. Can I train a model using this A.I. with my current set-up?
2. If not, what is the minimum GPU & V-RAM requirement to train with a dataset of at least 75-150 pairs?

Thank you so much in advance!

**Comment by TRvlvr** [comment]
I fixed it!

I reduced the batch size from 4 to 2. This was just enough to get going! For anyone facing the same issue, append the training command with the following - 

_python train.py -i dataset/instrumentals -m dataset/mixtures -M 0.5 -g 0 -b 2 -B 2_
