### ISSUE TITLE
CUDA Out of memory while trying to use the pre-trained model

### ISSUE THREAD

**Issue by AlbyTree** [tsurumeso/vocal-remover#24]
If I try to use my gpu I get this error

`RuntimeError: CUDA out of memory. Tried to allocate 384.00 MiB (GPU 0; 2.00 GiB total capacity;
948.49 MiB already allocated; 275.23 MiB free; 1.06 GiB reserved in total by PyTorch)`

I have the following PC specs:

Operating System: Windows 10
Processor: Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
Graphic card: NVIDIA GeForce GTX 750 Ti with 2 GB of VRAM
System RAM: 8 GB

Is there a specific amount of VRAM needed to use the model on the gpu ?
Is there a way to lower the amount of VRAM ? 
I tried:

*  `python inference.py -i file.mp3 -g 0 -w 256` but I got the error
`Traceback (most recent call last):
  File "inference.py", line 104, in <module>  
    main()
  File "inference.py", line 64, in main
    pred = model.predict(X_window)
  File "C:\Users\AlbyTree\Vocal-Remover-DeepLearning\lib\nets.py", line 84, in predict
    assert h.size()[3] > 0
AssertionError`
* `python inference.py -i file.mp3 -g 0 -l 512` and it worked but the quality wasn't good as using the default values on the CPU

**Comment by TRvlvr** [comment]
I had the same issue when I tried running this on my old gaming laptop that also had a Nvidia GPU with 2GB's of RAM (bought it brand new in 2014). PyTorch and the newer Cuda drivers it comes with don't play well at all with older GPU's that have anything less than 4GB's of V-RAM.

**Comment by tsurumeso** [comment]
Try setting `--window_size` (`-w`) to 384 because it must be greater than 256.
I am trying to reduce memory usage recently. So it may be fixed in the next version.

**Comment by AlbyTree** [comment]
Thank you, now it works.

**Comment by FlashlightET** [comment]
train.py: error: unrecognized arguments: -w 384
